# AUTO-EXTRACTED from CMakeLists.txt (the Android target) — do not hand-edit.
# Shared by the Android 'raw_decoder' target and the desktop 'razbatch' target
# so the LibRaw source list cannot drift between platforms.
# Regenerate: see tools/extract_libraw_sources.sh
set(LIBRAW_SOURCES
        ${LIBRAW_PATH}/src/libraw_c_api.cpp
        ${LIBRAW_PATH}/src/libraw_datastream.cpp
        ${LIBRAW_PATH}/src/decoders/canon_600.cpp
        ${LIBRAW_PATH}/src/decoders/crx.cpp
        ${LIBRAW_PATH}/src/decoders/pana8.cpp
        ${LIBRAW_PATH}/src/decoders/decoders_dcraw.cpp
        ${LIBRAW_PATH}/src/decoders/sonycc.cpp
        ${LIBRAW_PATH}/src/decompressors/losslessjpeg.cpp
        ${LIBRAW_PATH}/src/decoders/decoders_libraw_dcrdefs.cpp
        ${LIBRAW_PATH}/src/decoders/olympus14.cpp
        ${LIBRAW_PATH}/src/decoders/decoders_libraw.cpp
        ${LIBRAW_PATH}/src/decoders/dng.cpp
        ${LIBRAW_PATH}/src/decoders/fp_dng.cpp
        ${LIBRAW_PATH}/src/decoders/fuji_compressed.cpp
        ${LIBRAW_PATH}/src/decoders/generic.cpp
        ${LIBRAW_PATH}/src/decoders/kodak_decoders.cpp
        ${LIBRAW_PATH}/src/decoders/load_mfbacks.cpp
        ${LIBRAW_PATH}/src/decoders/smal.cpp
        ${LIBRAW_PATH}/src/decoders/unpack_thumb.cpp
        ${LIBRAW_PATH}/src/decoders/unpack.cpp
        ${LIBRAW_PATH}/src/demosaic/aahd_demosaic.cpp
        ${LIBRAW_PATH}/src/demosaic/ahd_demosaic.cpp
        ${LIBRAW_PATH}/src/demosaic/amaze_demosaic_RT.cc
        ${LIBRAW_PATH}/src/demosaic/dcb_demosaic.cpp
        ${LIBRAW_PATH}/src/demosaic/dht_demosaic.cpp
        ${LIBRAW_PATH}/src/demosaic/misc_demosaic.cpp
        ${LIBRAW_PATH}/src/demosaic/xtrans_demosaic.cpp
        ${LIBRAW_PATH}/src/metadata/adobepano.cpp
        ${LIBRAW_PATH}/src/metadata/canon.cpp
        ${LIBRAW_PATH}/src/metadata/ciff.cpp
        ${LIBRAW_PATH}/src/metadata/cr3_parser.cpp
        ${LIBRAW_PATH}/src/metadata/epson.cpp
        ${LIBRAW_PATH}/src/metadata/exif_gps.cpp
        ${LIBRAW_PATH}/src/metadata/fuji.cpp
        ${LIBRAW_PATH}/src/metadata/identify_tools.cpp
        ${LIBRAW_PATH}/src/metadata/identify.cpp
        ${LIBRAW_PATH}/src/metadata/kodak.cpp
        ${LIBRAW_PATH}/src/metadata/leica.cpp
        ${LIBRAW_PATH}/src/metadata/makernotes.cpp
        ${LIBRAW_PATH}/src/metadata/mediumformat.cpp
        ${LIBRAW_PATH}/src/metadata/minolta.cpp
        ${LIBRAW_PATH}/src/metadata/misc_parsers.cpp
        ${LIBRAW_PATH}/src/metadata/nikon.cpp
        ${LIBRAW_PATH}/src/metadata/normalize_model.cpp
        ${LIBRAW_PATH}/src/metadata/olympus.cpp
        ${LIBRAW_PATH}/src/metadata/hasselblad_model.cpp
        ${LIBRAW_PATH}/src/metadata/p1.cpp
        ${LIBRAW_PATH}/src/metadata/pentax.cpp
        ${LIBRAW_PATH}/src/metadata/samsung.cpp
        ${LIBRAW_PATH}/src/metadata/sony.cpp
        ${LIBRAW_PATH}/src/metadata/tiff.cpp
        ${LIBRAW_PATH}/src/postprocessing/aspect_ratio.cpp
        ${LIBRAW_PATH}/src/postprocessing/dcraw_process.cpp
        ${LIBRAW_PATH}/src/postprocessing/mem_image.cpp
        ${LIBRAW_PATH}/src/postprocessing/postprocessing_aux.cpp
        ${LIBRAW_PATH}/src/postprocessing/postprocessing_utils_dcrdefs.cpp
        ${LIBRAW_PATH}/src/postprocessing/postprocessing_utils.cpp
        ${LIBRAW_PATH}/src/preprocessing/ext_preprocess.cpp
        ${LIBRAW_PATH}/src/preprocessing/raw2image.cpp
        ${LIBRAW_PATH}/src/preprocessing/subtract_black.cpp
        ${LIBRAW_PATH}/src/tables/cameralist.cpp
        ${LIBRAW_PATH}/src/tables/colorconst.cpp
        ${LIBRAW_PATH}/src/tables/colordata.cpp
        ${LIBRAW_PATH}/src/tables/wblists.cpp
        ${LIBRAW_PATH}/src/utils/curves.cpp
        ${LIBRAW_PATH}/src/utils/decoder_info.cpp
        ${LIBRAW_PATH}/src/utils/init_close_utils.cpp
        ${LIBRAW_PATH}/src/utils/open.cpp
        ${LIBRAW_PATH}/src/utils/phaseone_processing.cpp
        ${LIBRAW_PATH}/src/utils/read_utils.cpp
        ${LIBRAW_PATH}/src/utils/thumb_utils.cpp
        ${LIBRAW_PATH}/src/utils/utils_dcraw.cpp
        ${LIBRAW_PATH}/src/utils/utils_libraw.cpp
        ${LIBRAW_PATH}/src/write/apply_profile.cpp
        ${LIBRAW_PATH}/src/write/file_write.cpp
        ${LIBRAW_PATH}/src/write/tiff_writer.cpp
        ${LIBRAW_PATH}/src/x3f/x3f_parse_process.cpp
        ${LIBRAW_PATH}/src/x3f/x3f_utils_patched.cpp
)
